blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/masa10-f/HumanCompiler/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 💼 Commercial License Inquiry
    url: mailto:masa1063fuk@gmail.com
    about: Contact us for commercial licensing options
  - name: 📚 Documentation
    url: https://github.com/masa10-f/HumanCompiler#readme
    about: Read the project documentation
  - name: 🔧 API Documentation
    url: https://humancompiler-api-masa.fly.dev/docs
    about: View interactive API documentation
