repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # MyPy for type checking (disabled in pre-commit, runs in CI)
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: python -m mypy
  #       language: system
  #       types: [python]
  #       args: [src, --config-file=pyproject.toml]
  #       pass_filenames: false

  # Bandit for security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [-r, src, -q]
        pass_filenames: false

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
