repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # MyPy for type checking
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'cd apps/api && python -m mypy src --config-file=pyproject.toml'
        language: system
        types: [python]
        pass_filenames: false

  # Pytest for running tests
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd apps/api && PYTHONPATH=src python -m pytest'
        language: system
        types: [python]
        pass_filenames: false

  # Bandit for security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [-r, src, -q]
        pass_filenames: false

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
